### ISSUE TITLE
Scene favola - vedere se si riesce a bloccare la visualizzazione in landscape

### ISSUE THREAD

**Issue by pietrogiarola** [DavideMiozzi/vdfApp#7]
Ho provato ad importare il plug screenOrientation, ma comunque su device non succede nulla

**Comment by pietrogiarola** [comment]
per i telefoni bloccare l'orientamento di tutta l'app a verticale, così ci risparmiamo css per visualizzare tutto orizzontale.
L'unica pagina orizzontale rimane la favola stessa

**Comment by DavideMiozzi** [comment]
anche questa mi sembra sia fatta
